# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT

sudo ex +"%s@DPkg@//DPkg" -cwq /etc/apt/apt.conf.d/70debconf
sudo dpkg-reconfigure debconf -f noninteractive -p critical
echo '* libraries/restart-without-asking boolean true' | sudo debconf-set-selections > /dev/null
echo 'printf \"\\n\"' | sudo tee -a /etc/update-motd.d/10-uname > /dev/null
echo 'exec neofetch' | sudo tee -a /etc/update-motd.d/10-uname > /dev/null

sudo apt-get update
sudo apt-get install neofetch -y

for bin in cfssl cfssl-certinfo cfssljson
do
  echo "Installing $bin..."
  curl -sSL https://pkg.cfssl.org/R1.2/${bin}_linux-amd64 > /tmp/${bin}
  sudo install /tmp/${bin} /usr/local/bin/${bin}
done

SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "bento/debian-10"
  config.vm.hostname = "python"
  config.vm.provision "shell", inline: $script, privileged: false

  # Expose the api to the host
  # config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true, host_ip: "127.0.0.1"

  ["vmware_desktop"].each do |p|
    config.vm.provider p do |v|
      v.vmx["memsize"] = "2048"
      # v.vmx["ethernet0.pcislotnumber"] = "32"
    end
  end
end
